FROM node:8-alpine

WORKDIR '/home/app'

# Copy all local files into the image.

COPY package.json /home/app

RUN set -x \
  && npm install \
  && npm install -g serve

COPY . /home/app

RUN npm run build

CMD [ "serve", "-s", "build" ]

EXPOSE 3000
